[package]
name = "paper-manager"
version = "0.1.0"
authors = ["rdodd"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.6", features = ["postgres"] }
rocket = "0.4.2"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["tera_templates"]
